theme: jekyll-theme-cayman

# Name of website
title: 小智的每周总结

# Short description of your site
description: Conor's Weekly Summary

# List of links in the navigation bar
navbar-links:
  Home: "README.md"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "weekly/assets/avatar/avatar.png"
